### PR TITLE
Styling of reports using existing TI statistics-css.

### PR DESCRIPTION
**Pull request by shelemiah**

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Thats looking great - thanks for the input so far!

I made a small tweak on the header bar - if you have any suggestions as to how to make it sit better that would be great.

What do you think about making "orders by" (day etc) sections into progress bars or pie charts? The hours one is especially long so could do with a better layout.

**Comment by shelemiah** [comment]
Yes.. the "orders by" section would look more presentable as charts. Let me look into that.

**Comment by ryanmitchell** [comment]
Just checking if you have had a chance to work on this? If not I may be able to find some time this week.

**Comment by ryanmitchell** [comment]
Did you ever get to look into the charts?

**Comment by shelemiah** [comment]
Unfortunately I did not. I should have some time available this weekend; will update you then.

**Comment by ryanmitchell** [comment]
Let me know if you've made any progress - keen to release this to the marketplace as it meets a real need. It could go without the graphs if you haven't had time for that yet.

**Comment by ryanmitchell** [comment]
I've worked on the graphs and pulled these changes into the main extension, so closing this off.

**Pull request closed without merging**
